[package]
name = "longan-labs-i2c-can"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embedded-hal-async = "0.2.0-alpha.0"
arrayvec = { version = "0.7", default-features = false }
